### ISSUE TITLE
'vonage' is not defined

### ISSUE THREAD

**Issue by musano97** [Defaultik/sms_spoofer#12]
im having issue : 

Traceback (most recent call last):
  File "C:\Users\pc\Desktop\web dev\sms_spoofer-main\sms_spoofer.py", line 208, in <module>
    menu()
  File "C:\Users\pc\Desktop\web dev\sms_spoofer-main\sms_spoofer.py", line 77, in menu
    dial_number()
  File "C:\Users\pc\Desktop\web dev\sms_spoofer-main\sms_spoofer.py", line 114, in dial_number
    send_sms(sms_victim_number, sms_sender_name, sms_text)
  File "C:\Users\pc\Desktop\web dev\sms_spoofer-main\sms_spoofer.py", line 89, in send_sms
    client = vonage.Client(
NameError: name 'vonage' is not defined 

platform windows 

api setup correctly

**Comment by Defaultik** [comment]
Hi 👋,
Thank you very much for reporting and detailed explanation!

I'm glad to announce that the problem has been fixed and the problem was related to changes in the latest updates of Python.
**For properly work of the program, you should reinstall it.**
